Updated

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -67,77 +67,88 @@ jobs:
 #        env:
 #          TEST_PHP_ARGS: "-q" #do not try to submit failures
 #        run: make test TESTS=--show-diff
-
-  windows:
+  windows-understand:
     runs-on: windows-2022
-    continue-on-error: false
-    strategy:
-      fail-fast: false
-      matrix:
-        php: ['8.1']
-        ts: ['nts']
     steps:
-      - name: Checkout
-        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
-      - name: Install PHP ${{ matrix.php }}-${{ matrix.ts }}
-        id: setup-php-sdk
-        uses: php/setup-php-sdk@v0.12
-        with:
-          version: ${{ matrix.php }}
-          arch: x64
-          ts: ${{ matrix.ts }}
-      - name: Install dependencies
-        uses: ilammy/msvc-dev-cmd@v1
-        with:
-          arch: x64
-          toolset: ${{ steps.setup-php-sdk.outputs.toolset }}
-      - name: list extensions
+      - name: Locate libcurl.lib
         run: |
-          php -m
-      - name: test curl
+          Get-ChildItem -Path C:\ -Filter libcurl.lib -Recurse -ErrorAction SilentlyContinue
+      - name: Locate libcurl_a.lib
         run: |
-          curl --version
-      - name: echo %PATH%
+          Get-ChildItem -Path C:\ -Filter libcurl_a.lib -Recurse -ErrorAction SilentlyContinue
+      - name: Locate easy.h
         run: |
-          echo %PATH%
-      - name: phpize
-        run: |
-          phpize
-      - name: configure
-        run: |
-          ./configure --enable-swo --with-prefix=${{ steps.setup-php-sdk.outputs.prefix }}
-      - name: Build
-        run: |
-          nmake
-      - name: Test
-        env:
-          TEST_PHP_ARGS: "-q"
-        run: nmake test TESTS=--show-diff
-      - name: Get Compiler Version + Build Name
-        shell: bash
-        run: |
-          case "$VisualStudioVersion" in
-            16.*) COMPILER="vs16";;
-            17.*) COMPILER="vs17";;
-            *) echo "Unknown MSVC version: $VisualStudioVersion"; exit 1;;
-          esac
-          echo "Detected Compiler: $COMPILER"
-          SAFE_REF_NAME="${GITHUB_REF_NAME//\//-}"
-          BUILD_NAME="php_swo-${SAFE_REF_NAME}-${{matrix.php}}-${{matrix.ts}}-$COMPILER-x64"
-          echo "Build Name: $BUILD_NAME"
-          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
-
-      - name: Rename and copy binaries
-        run: |
-          md binaries\${{env.BUILD_NAME}}
-          $file = Get-ChildItem -Path x64 -Recurse -Filter php_opentelemetry.dll
-          Copy-Item -Path $file.FullName -Destination "binaries\${{env.BUILD_NAME}}\${{env.BUILD_NAME}}.dll"
-      - name: Find
-        run: |
-          Get-ChildItem -Path binaries -Recurse -Force | ForEach-Object { $_.FullName }
-      - name: Upload artifacts
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
-        with:
-          name: ${{env.BUILD_NAME}}
-          path: ext\binaries\${{env.BUILD_NAME}}\${{env.BUILD_NAME}}.dll
-          if-no-files-found: error
+          Get-ChildItem -Path C:\ -Filter easy.h -Recurse -ErrorAction SilentlyContinue
+#  windows:
+#    runs-on: windows-2022
+#    continue-on-error: false
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        php: ['8.1']
+#        ts: ['nts']
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
+#      - name: Install PHP ${{ matrix.php }}-${{ matrix.ts }}
+#        id: setup-php-sdk
+#        uses: php/setup-php-sdk@v0.12
+#        with:
+#          version: ${{ matrix.php }}
+#          arch: x64
+#          ts: ${{ matrix.ts }}
+#      - name: Install dependencies
+#        uses: ilammy/msvc-dev-cmd@v1
+#        with:
+#          arch: x64
+#          toolset: ${{ steps.setup-php-sdk.outputs.toolset }}
+#      - name: list extensions
+#        run: |
+#          php -m
+#      - name: test curl
+#        run: |
+#          curl --version
+#      - name: Locate libcurl.lib
+#        run: |
+#          Get-ChildItem -Path C:\ -Filter libcurl.lib -Recurse -ErrorAction SilentlyContinue
+#      - name: phpize
+#        run: |
+#          phpize
+#      - name: configure
+#        run: |
+#          ./configure --enable-swo --with-prefix=${{ steps.setup-php-sdk.outputs.prefix }}
+#      - name: Build
+#        run: |
+#          nmake
+#      - name: Test
+#        env:
+#          TEST_PHP_ARGS: "-q"
+#        run: nmake test TESTS=--show-diff
+#      - name: Get Compiler Version + Build Name
+#        shell: bash
+#        run: |
+#          case "$VisualStudioVersion" in
+#            16.*) COMPILER="vs16";;
+#            17.*) COMPILER="vs17";;
+#            *) echo "Unknown MSVC version: $VisualStudioVersion"; exit 1;;
+#          esac
+#          echo "Detected Compiler: $COMPILER"
+#          SAFE_REF_NAME="${GITHUB_REF_NAME//\//-}"
+#          BUILD_NAME="php_swo-${SAFE_REF_NAME}-${{matrix.php}}-${{matrix.ts}}-$COMPILER-x64"
+#          echo "Build Name: $BUILD_NAME"
+#          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
+#
+#      - name: Rename and copy binaries
+#        run: |
+#          md binaries\${{env.BUILD_NAME}}
+#          $file = Get-ChildItem -Path x64 -Recurse -Filter php_opentelemetry.dll
+#          Copy-Item -Path $file.FullName -Destination "binaries\${{env.BUILD_NAME}}\${{env.BUILD_NAME}}.dll"
+#      - name: Find
+#        run: |
+#          Get-ChildItem -Path binaries -Recurse -Force | ForEach-Object { $_.FullName }
+#      - name: Upload artifacts
+#        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+#        with:
+#          name: ${{env.BUILD_NAME}}
+#          path: ext\binaries\${{env.BUILD_NAME}}\${{env.BUILD_NAME}}.dll
+#          if-no-files-found: error
