enabled

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,61 +14,61 @@ defaults:
     working-directory: ext
 
 jobs:
-  linux:
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        php: [ '8.1', '8.2', '8.3', '8.4' ]
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
-      - name: Setup PHP
-        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2
-        with:
-          php-version: ${{ matrix.php }}
-      - name: Install libcurl
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y libcurl4-openssl-dev curl
-        shell: bash
-      - name: Build
-        run: |
-          phpize
-          ./configure
-          make
-      - name: Test
-        env:
-          TEST_PHP_ARGS: "-q" #do not try to submit failures
-        run: make test TESTS=--show-diff
-
-  macos:
-    runs-on: macos-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        php: [ '8.1', '8.2', '8.3', '8.4' ]
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
-
-      - name: Setup PHP
-        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2
-        with:
-          php-version: ${{ matrix.php }}
-
-      - name: build
-        run: |
-          phpize
-          ./configure
-          make
-
-      - name: test
-        env:
-          TEST_PHP_ARGS: "-q" #do not try to submit failures
-        run: make test TESTS=--show-diff
+#  linux:
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        php: [ '8.1', '8.2', '8.3', '8.4' ]
+#
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
+#      - name: Setup PHP
+#        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2
+#        with:
+#          php-version: ${{ matrix.php }}
+#      - name: Install libcurl
+#        run: |
+#          sudo apt-get update
+#          sudo apt-get install -y libcurl4-openssl-dev curl
+#        shell: bash
+#      - name: Build
+#        run: |
+#          phpize
+#          ./configure
+#          make
+#      - name: Test
+#        env:
+#          TEST_PHP_ARGS: "-q" #do not try to submit failures
+#        run: make test TESTS=--show-diff
+#
+#  macos:
+#    runs-on: macos-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        php: [ '8.1', '8.2', '8.3', '8.4' ]
+#
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
+#
+#      - name: Setup PHP
+#        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2
+#        with:
+#          php-version: ${{ matrix.php }}
+#
+#      - name: build
+#        run: |
+#          phpize
+#          ./configure
+#          make
+#
+#      - name: test
+#        env:
+#          TEST_PHP_ARGS: "-q" #do not try to submit failures
+#        run: make test TESTS=--show-diff
 
   windows:
     runs-on: windows-2022
@@ -93,40 +93,40 @@ jobs:
         with:
           arch: x64
           toolset: ${{ steps.setup-php-sdk.outputs.toolset }}
-#      - name: Build
-#        run: |
-#          phpize
-#          ./configure
-#          nmake
-#      - name: Test
-#        env:
-#          TEST_PHP_ARGS: "-q"
-#        run: nmake test TESTS=--show-diff
-#      - name: Get Compiler Version + Build Name
-#        shell: bash
-#        run: |
-#          case "$VisualStudioVersion" in
-#            16.*) COMPILER="vs16";;
-#            17.*) COMPILER="vs17";;
-#            *) echo "Unknown MSVC version: $VisualStudioVersion"; exit 1;;
-#          esac
-#          echo "Detected Compiler: $COMPILER"
-#          SAFE_REF_NAME="${GITHUB_REF_NAME//\//-}"
-#          BUILD_NAME="php_swo-${SAFE_REF_NAME}-${{matrix.php}}-${{matrix.ts}}-$COMPILER-x64"
-#          echo "Build Name: $BUILD_NAME"
-#          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
-#
-#      - name: Rename and copy binaries
-#        run: |
-#          md binaries\${{env.BUILD_NAME}}
-#          $file = Get-ChildItem -Path x64 -Recurse -Filter php_opentelemetry.dll
-#          Copy-Item -Path $file.FullName -Destination "binaries\${{env.BUILD_NAME}}\${{env.BUILD_NAME}}.dll"
-#      - name: Find
-#        run: |
-#          Get-ChildItem -Path binaries -Recurse -Force | ForEach-Object { $_.FullName }
-#      - name: Upload artifacts
-#        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
-#        with:
-#          name: ${{env.BUILD_NAME}}
-#          path: ext\binaries\${{env.BUILD_NAME}}\${{env.BUILD_NAME}}.dll
-#          if-no-files-found: error
+      - name: Build
+        run: |
+          phpize
+          ./configure
+          nmake
+      - name: Test
+        env:
+          TEST_PHP_ARGS: "-q"
+        run: nmake test TESTS=--show-diff
+      - name: Get Compiler Version + Build Name
+        shell: bash
+        run: |
+          case "$VisualStudioVersion" in
+            16.*) COMPILER="vs16";;
+            17.*) COMPILER="vs17";;
+            *) echo "Unknown MSVC version: $VisualStudioVersion"; exit 1;;
+          esac
+          echo "Detected Compiler: $COMPILER"
+          SAFE_REF_NAME="${GITHUB_REF_NAME//\//-}"
+          BUILD_NAME="php_swo-${SAFE_REF_NAME}-${{matrix.php}}-${{matrix.ts}}-$COMPILER-x64"
+          echo "Build Name: $BUILD_NAME"
+          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
+
+      - name: Rename and copy binaries
+        run: |
+          md binaries\${{env.BUILD_NAME}}
+          $file = Get-ChildItem -Path x64 -Recurse -Filter php_opentelemetry.dll
+          Copy-Item -Path $file.FullName -Destination "binaries\${{env.BUILD_NAME}}\${{env.BUILD_NAME}}.dll"
+      - name: Find
+        run: |
+          Get-ChildItem -Path binaries -Recurse -Force | ForEach-Object { $_.FullName }
+      - name: Upload artifacts
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+        with:
+          name: ${{env.BUILD_NAME}}
+          path: ext\binaries\${{env.BUILD_NAME}}\${{env.BUILD_NAME}}.dll
+          if-no-files-found: error
